### ISSUE TITLE
Update the path attribute in tasks.

### ISSUE THREAD

**Issue by LennartOlsson** [AMSP-04/NETN-ETR#11]
The specification of the path in MoveToLocation and MoveToUnit needs to be updated to match the new NETN-SE FOM module definitions of pathes.

**Comment by hendersonhc** [comment]
When the Waypoints (path) is replaced by a reference to a object in the NETN-SE FOM module then always a path is needed. It should also be possible to define a ad-hoc route by defining a few points without defining a path and include this in the message itself.
To discuss further.

**Comment by LennartOlsson** [comment]
The variant record have a polygonal chain or a UUID reference to a registred GeoObject.Path

**Comment by LennartOlsson** [comment]
Updated the FOM module.

**Comment by hendersonhc** [comment]
Note that the waypoint list is not always a path. For example when the movetype is on road then there could be a complex route on the road between two consecutive waypoints. This road is in that case determined by the simulator that is handling the task.  The simulator knows the terrain with the road map that is used. The user only gives a few points through which the movement should be going.
