### ISSUE TITLE
Change VariantStruct datatypes to two parameters.

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-ETR#17]
Use one for the basic path/point... and one **optional** for referencing objects with uuid. Update documentation.

**Comment by LennartOlsson** [comment]
Uploaded

**Comment by lofstrandbjorn** [comment]
Change name of Destination and Path to LocationUuid and WaypointsUuid

**Comment by bergtwvd** [comment]
The semantics in ETR MoveToLocation and MoveToEntity has been updated to clarify the interpretation of the parameters Locaction/LocationUuiD and Path/PathUuid.
