### ISSUE TITLE
Clarify semantics of CapabilitiesSupported

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-ETR#22]
In the returned list of names of interaction classes for ETR tasks
1. Does this include ETR_SimCon and ETR_TaskManagement classes (I think it should)?!
2. Are the names fully qualified names such as "HLAinteractionClassRoot.ETR_Root.ETR_Task.*" or simply "MoveToLocation", "MagicMove" etc. ??

**Comment by bergtwvd** [comment]
For item 1: ETR_SimCon and ETR_TaskManagement are required. The ETR description states: The sender `SHALL support all ETR TaskManagement and ETR SimCon classes.`

**Comment by bergtwvd** [comment]
For item 2: the names are base names and not FQ names. The interaction names must therefore be (and are) unique in the NETN-ETR.

**Comment by lofstrandbjorn** [comment]
Semantics clarified as:

Provides the set of ETR_Task, ETR_SimCon and ETR_Report interactions that the federate modelling the entity supports. This interaction is in response to a QueryCapabilitiesSupported, using the same Taskee and Tasker. The names returned is the base interaction class name and not fully qualified.
