### ISSUE TITLE
Change QueryCapabilitiesSupported and CapabilitiesSupported to be TaskManagement

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-ETR#26]
Is there a rationale or reason for QueryCapabilitiesSupported and CapabilitiesSupported to be SimCon interactions and not TaskManagement?

**Comment by bergtwvd** [comment]
Rationale:
- The management interactions are required for any plugin;
- The tasks and reports are optional.

Otherwise there is no way to programmatically find out what is supported by a plugin.

**Comment by lofstrandbjorn** [comment]
I understand that Tasks and Reports are optional but what is the difference between SimCon and TaskManagement interactions and why should the QueryCapabilitiesSupported not be a TaskManagement interaction?

**Comment by bergtwvd** [comment]
Some time ago we had a discussion if MagicMove and MagicResource should be part of ETR. We concluded maybe not, but keep them in for now. And put them aside under Simulation Control - SimCon.

For reasons - currently - unknown the two capability related tasks ended up there too. Need to check why.

**Comment by martin-s** [comment]
I agree with @lofstrandbjorn and propose to move the capability interactions to _task management_ group.
Second, magic move and magic resource belong to the _task_ group, IMHO.

Regarding the _SimCon_ group, I would see a new NETN SMC, for example. As its not related to a specific entity, at first.

**Comment by lofstrandbjorn** [comment]
QueryCapabilitiesSupported and CapabilitiesSupported moved to TaskManagement
