### ISSUE TITLE
Relax requirement on provided parameters

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-ETR#27]
Currently the ETR description states that the sender `SHALL provide all interaction class parameters when sending an ETR interaction.`

This is potentially asking for problems when a federate does not comply. To make the use of the ETR more robust, this requirement should be relaxed, and actually reversed: make parameters optional as much as possible, and define sensible defaults. The same approach is used in NETN-AIS, leading to much slimmer and easier to develop federates.

**Comment by lofstrandbjorn** [comment]
Agree. Create feature branch, implement proposed changes and make a pull-req. review.

**Comment by lofstrandbjorn** [comment]
LO & Henk to post list of optional parameters in this discussion.

**Comment by LennartOlsson** [comment]
Added Required/Optional in attached ETR-ReqOpt-LO.pdf. There are a lot of typos in the xml file, mostly corrected in the attached file.
[ETR-ReqOpt-LO.pdf](https://github.com/AMSP-04/NETN-ETR/files/5028263/ETR-ReqOpt-LO.pdf)

**Comment by bergtwvd** [comment]
Lennart's optional list is mostly fine. One issue we have is mentioned in https://github.com/AMSP-04/NETN-ETR/issues/38.

Henk will create a proposal for the FOM update, while at time fixing https://github.com/AMSP-04/NETN-ETR/issues/38.

**Comment by bergtwvd** [comment]
Done
