### ISSUE TITLE
CapabilitiesSupported should use an Enum type for CapabilityNames

### ISSUE THREAD

**Issue by linusonline** [AMSP-04/NETN-ETR#30]
The attribute CapabilityNames of interaction CapabilitiesSupported is now an array of strings. This leaves a lot of room for interpretation as to the exact contents of the strings, as well as which interactions are considered "capabilities". Since the set of capabilities is already bounded by the FOM itself, this should probably be an enum data type instead.

**Comment by bergtwvd** [comment]
Yes, this is fine for me.

**Comment by bergtwvd** [comment]
I think the request to perfectly fine for Edition B.  What is the reason to move it to C?

**Comment by lofstrandbjorn** [comment]
Solve in C since HLA4 allows mergin of enum datatypes
