### ISSUE TITLE
Clarify semantics of EstablishCheckpoint

### ISSUE THREAD

**Issue by linusonline** [AMSP-04/NETN-ETR#31]
Various minor language errors to be corrected (also applies to OperateCheckpoint semantics). In particular, overuse of "shall".

More specifically:
"The Duration defines the time when the checkpoint is active by the specified Taskee."

Suggest replacing this with:
"Duration specifies the length of time after the establishment of the check point during which it will be active and operated by the Taskee."

**Comment by LennartOlsson** [comment]
Updated the semantics for EstablishCheckpoint

**Comment by linusonline** [comment]
Reviewed commit on develop. Still some general language issues, but I'm ok with it.
