### ISSUE TITLE
How should JamCommunication be executed?

### ISSUE THREAD

**Issue by ChristianPick** [AMSP-04/NETN-ETR#34]
According to the tasks description it tasks an entity to jam a communication network in a specific area.  How should this be done? A communication network is a _logical_ network - jamming is always against a _physical_ network infrastructure. As the physical networks used to transport data within a logical network can use multiple technologies (ethernet, wlan, radio, laser-links...) and nodes within a physical network could transport data from several communication networks in parallel it is technically not possible to jam a specific communication network - only the infrastructure (or parts of it) could be jammed with the effect that all commincation networks using this infrastructure will be affected. So how should this command be interpreted / executed by an entity?

Shouldn't it be a JamRadio task? A tasked entity could create something like a JammerBeam as a counterpart to a RPR RadioEmitter. This could be evaluated by a simulation of the physical networks' links within the NETN-COM module. (In a similar way a JamRadar task could work to open up a discussion about electronic warfare and countermeasures...)

**Comment by bergtwvd** [comment]
I agree that the working of this task is not clear.  I think we try to establish a simple mechanism to introduce jamming effects, rather that modeling and simulating the physical aspects of jamming. E.g. switch on/off radio communication in a specific area.

If this is the idea, then shouldn't every federate interpret the JamCommunication interaction to disable communication for entities involved? Or do we expect follow-up interactions from the federate the manages the tasked entity? And what interaction will that be?

**Comment by ChristianPick** [comment]
To achieve a simple mechanism for this kind of jamming effects it would be sufficient to have a "SimplifiedJammingEffect" object within the NETN-COM module. The effect could be applied to all entities in a specific area by the communication simulation model. It could refer to the communication network or to a physical network. As it is no longer a task to an entity there would be no problem how the entity should execute it...

I still see a need for a JamRadio (and JamRadar etc.) tasks, but they should be clear in their meaning and as an order to do something it should not include the result of operation.

**Comment by bergtwvd** [comment]
It all comes down to: _what does the user want?_

I suspect that in an exercise like Viking the "user" wants to have a simple mechanism to disrupt radio communication in a certain area. E.g. AIS or other types of simulated radio messages are blocked, and hence not forwarded to live C2 systems.  This is more effects driven. But I am guessing here ....  
I guess that the existing ETR task is intended for this effect..

And then we have the modeling and simulation at the logical and physical level, covered by the FOM already.
How would these JamXXX tasks look like?

**Comment by ChristianPick** [comment]
To simply disrupt the communication in a certain area I think my proposal to have a JammigEffect-Object within the NETN-COM module is the better way. Why should a user task an entity to do so? He doesn't want an entity to jam the area - he wants the effect of jammed communication in the area regardless who is doing the jamming and how it is done.
By using an object instead of a task (interaction) the effect would be described in a persistant way - even a late joiner will be jammed. For me this would be a clean and straigthforward solution.

**Comment by ChristianPick** [comment]
If I want to task an entity to jam a target (entity/location/area) I would order it by specifying the target, the frequency used (in case of radio/radar jamming) and the type/mode of jamming (e.g. noise, offset etc. in case of radar). It is up to the sender to select the right frequencys / modes to achieve the effect he wants. Maybe a "generic" mode could be used to allow the receiver to autoselect the frequency/mode. I'm not an expert in electronic warfare - but I would expect this data in a real world order...

**Comment by bergtwvd** [comment]
> To simply disrupt the communication in a certain area I think my proposal to have a JammigEffect-Object within the NETN-COM module is the better way. Why should a user task an entity to do so? He doesn't want an entity to jam the area - he wants the effect of jammed communication in the area regardless who is doing the jamming and how it is done.
> By using an object instead of a task (interaction) the effect would be described in a persistant way - even a late joiner will be jammed. For me this would be a clean and straigthforward solution.

Although I understand the modelling can be done this way, I am thinking of a task to initiate and terminate the jamming. The taskee would create/delete such an object. There could be other parameters such as the duration. And the taskee has to be near the area.  Or it can be a simcon task such as magic move. This way we can use the ETR scheme.

**Comment by bergtwvd** [comment]
> If I want to task an entity to jam a target (entity/location/area) I would order it by specifying the target, the frequency used (in case of radio/radar jamming) and the type/mode of jamming (e.g. noise, offset etc. in case of radar). It is up to the sender to select the right frequencys / modes to achieve the effect he wants. Maybe a "generic" mode could be used to allow the receiver to autoselect the frequency/mode. I'm not an expert in electronic warfare - but I would expect this data in a real world order...

I guess we need objects to publish the results of the jammimg, or will the jamming federate need to update the NETN COM objects?

**Comment by ChristianPick** [comment]
I think there are different levels of fidelity / realism. The simpliest way would be as described an object describing the final effect of jamming within NETN-COM. This object could be published / unpublished by whoever wants such an effect to take place.

The next level would be to task an entity using NETN-ETR to do so. In such a case the entity takes care of the lifetime of the NETN-COM object describing the final effect. The question in such a case is how is the entity tasked ("jam logical network" or "jam physical infrastructure"). For the reason I stated in my first post I don't like "jam logical network" tasks. Leaving it to the entity's simulation to calculate / generate the final effect of physical jamming on the network infrastructure could be an intermediate solution, but doing so in a realistic manner will be very difficult for the simulation as it usually does not include a link-level network simulation. (Otherwise it would not be necessary to use dedicated federates to do so based on NETN-COM).

The next and highest level of fidelity would be to task an entity to jam the physical infrastructure. The taskee creates objects (NETN-COM) describing the physical parameters of the jamming operation within the environment. The link-level simulations within NETN-COM uses this information to calculate the effect on the physical infrastructure. It is not needed to publish the effect as separate objects in such a case. This is a realistic approach and reflects the processes as they are. BUT it is very complicated if you just want to achieve the effect of disrupted communication for demonstration purposes.

Therefore I think a mixture of these alternatives should be used: (Optional) Objects describing the final effect of jamming in parallel to the possibility to describe the physical jamming operation. At the end it is up to the federation aggreement and the capabilities of the simulations in use to decide which way to go.

NETN-COM needs to be extended by the objects to describe jamming. As NETN-COM is currently incomplete in the description of the physical parameters I propose to use the lowest level of fidelity for the first demonstrations and to extend more sophisticated jamming capabilities in the next version. For demo purposes a "JamAllCommunication" task could be implemented in ETR, but it should be replaced in the next version.

**Comment by lofstrandbjorn** [comment]
Proposal: Change the name JamCommunication to be more effects-based. Eg. DisruptCommunication. Change the parameters to remove "jam". Is there a need to JamRadio task?

**Comment by lofstrandbjorn** [comment]
> To simply disrupt the communication in a certain area I think my proposal to have a JammigEffect-Object within the NETN-COM module is the better way. Why should a user task an entity to do so? He doesn't want an entity to jam the area - he wants the effect of jammed communication in the area regardless who is doing the jamming and how it is done.
> By using an object instead of a task (interaction) the effect would be described in a persistant way - even a late joiner will be jammed. For me this would be a clean and straigthforward solution.

I agree that the result of a task for creating effects should be an object. We need to revisit NETN-COM for this.

**Comment by bergtwvd** [comment]
Done.
