### ISSUE TITLE
Update ETR documentation

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-ETR#41]
I.e.
- [x] update figures
- [x] update associated text
- [x] update description on optional/required parameters

**Comment by lofstrandbjorn** [comment]
Tom, will you take the lead on updating this documentation?

**Comment by bergtwvd** [comment]
Yes. I created this issue to collect all of the documentation related-items we come across for this module, and add them to the checkbox-list. Then I can update them in one go.

**Comment by lofstrandbjorn** [comment]
perfect

**Comment by bergtwvd** [comment]
Done.
