### ISSUE TITLE
Change ETR Tasks to use Geodetic references to locations

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-ETR#43]

**Comment by bergtwvd** [comment]
Currently radians are used, without defining where the origin is. For the record, `0` heading is along the x-axis (east), going anti-clock-wise. Neither is defined if the range should be (-PI, PI], or [0, 2PI), or ....

**Comment by lofstrandbjorn** [comment]
Tasking is using geocentric XYZ for positions and degrees relative to true north for heading orientation.
