### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-ETR#45]
Use of optionals should be maximised. All tasks should be reviewed for optionals. Propose at least:

ETR_Task
- StartWhen (default: 00000000000000.000)
- TaskMode (default: NonConcurrentMode)

MoveToEntity, MoveToLocation, Patrol
- MoveType (default: CrossCountry)

Patrol:
- PatrolType (default: Other)

Wait:
- Duration (default: 0)

TurnToHeading:
- Heading (default: 0)

**Comment by lofstrandbjorn** [comment]
Fixed
