### ISSUE TITLE
Request to change Tasker parameter datatype from callsign to UUID

### ISSUE THREAD

**Issue by ngcheeki** [AMSP-04/NETN-ETR#50]
While assessing the usage of the Entity Tasking and reporting interaction classes, we came crossed ETR-Task interaction class. We had some on the ETR_Task base classes

The parameters of the ETR_Task interaction class are defined as follows:
TaskId: TransactionId ;Required. Uniqie identifier for the task.
Taskee: UUID; Required. Reference to the entity that will execute the task.
Tasker: Callsign; Optional. Callsign of the commander of the task. If missing, the commander is undefined.
StartWhen:Datetime18; Required. Time when the task execution should start. Use the value 00000000000000.000 to indicate that the time is undefined.
Why: HLAunicodeString; Optional. A text describing the reason for this task.
TaskMode: TaskModeEnum8; Required. Determines the task mode.
CommunicationNetworkIds: ArrayOfText64 ;

1.  Why is the Taskee and Tasker instance identifier datatype is different? The Taskee is using UUID and the Tasker  is using callsign datatype? Furthermore, why is the Tasker parameter an optional parameter instead of a required field?

2. The Callsign for an simulated entity in an scenario may not be unique. Hence, I would proposed the Tasker datatype as UUID even though it is not readable.

May I propose to change the Tasker field to UUID and make it as a mandatory field?

Thanks.

**Comment by hendersonhc** [comment]
The format of the Tasker is more free (callsign/string) so the user can put in everything he want (name of a commander,, name of a group of tasks that belong to each other, simulator that is sending the task. etc.). All though it is defined as a callsign it is even not needed that is represent a simulation object.
Of course it is still possible if the Tasker represents a unique simulated object with a UUID to fill the Tasker with a UUID string. It is up to the sender of the task. In the handling simulator the Tasker is only used to report it back in the Task report that belongs to the Task and is not relevant for the simulation itself. So it can be optional. When the Tasker is not defined in the Task then also in the returning Task reports that belongs to that task it will be  not defined.

**Comment by lofstrandbjorn** [comment]
This is an optional parameter representing a Unit or Simulated Entity sending the task. UUID is used as the identifier.
