### ISSUE TITLE
Add semantics of heading in FOM datatype description

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-ETR#53]
I.e. what is heading '0'?

Heading `0 deg`  in tasks refers to `East`. 

Heading `90 deg` in tasks refers to `North`.

See https://github.com/AMSP-04/NETN-ETR/issues/43.

**Comment by lofstrandbjorn** [comment]
It is clarified in semantics. 0 deg means true north. 90 deg means east, 180 south, 270 west.
The direction is measured clockwise relative to the true north. Calculate values outside the range [0, 360) as modulo 360.
