### ISSUE TITLE
Request: Support to save state of a task

### ISSUE THREAD

**Issue by OscBer97** [AMSP-04/NETN-ETR#54]
Request to be able to save the current state of tasks. 
In the current implementation it is only possible to know if a task is in queue to be started or if it is started. But we wish to be able to know the current state and progress of a task. This is so that we can save both the progress and state of a task, and then in the case of a crash be able to restore that state and progress without losing information.

**Comment by lofstrandbjorn** [comment]
Task progress of current tasks as well as planned and past tasks are represented for each entity.
