### ISSUE TITLE
Request clarification of ETR_SimCon parameters

### ISSUE THREAD

**Issue by bruno-g** [AMSP-04/NETN-ETR#55]
In the interaction class ETR_SimCon there is 2 parameters that I do not fully understand. 

TaskId (required TransactionId): what is the purpose of this parameter? Is-it to "reference" the interaction instance from another class / object? Or to use it inside another tool (such as an after action review tool)? what is the difference with the HLA interaction handle? 

Tasker (optional Callsign): what is the purpose of this parameter? is-it for example the name of the operator requesting a "magic move" (to save/store who did what)? 

Did these 2 parameters have an influence on the simulation? 

Thanks :)

**Comment by lofstrandbjorn** [comment]
TaskId is used to differentiate one event interaction from another uniquely. 
Tasker allows the receiver to determine the source of the task for display or logging purposes.
No influence on the simulation unless the receiver reject tasks based on callsign.
