### ISSUE TITLE
Add interaction MagicRestore 

### ISSUE THREAD

**Issue by hendersonhc** [AMSP-04/NETN-ETR#62]
Add beneath the ETR-SimCon a new interaction MagicRestore.

This interaction can be used to make the aggregate/entity fully operational again with no damage and all initial resources.
After the action the entity/aggregate is fully (100%) operational again.

 No extra parameters are needed (All needed parameters are defined in ETR_SimCon)

**Comment by lofstrandbjorn** [comment]
Introduce Reset interaction with parameters to indicate what to reset.

**Comment by lofstrandbjorn** [comment]
Reset introduced in NETN-LOG
