### ISSUE TITLE
Add interaction ChangePosture

### ISSUE THREAD

**Issue by hendersonhc** [AMSP-04/NETN-ETR#63]
Add the special task (beneath ETR_Task)) for aggregates to change the posture.

Parameter PostureEnum32 is  { DelibrateDefense, DeliberateAttack, HastyDefense, HastyAttack, Reconaissance, Rout, Travel }

The posture Is an important value in the aggregate level simulation since it influences the detection and firing process.
Note that in aggregate level simulation only an abstract aggregate is defined in the simulation without the under-lying subunits and platforms. In the aggregate warfare model simulation objects have combat power and combat vulnerability.

**Comment by lofstrandbjorn** [comment]
There is also the SetRulesOfEngagement to consider in this context. Let's have a telecon discussing this further.

**Comment by lofstrandbjorn** [comment]
Use Task Activity in tasking and published in CurrentTask. Use OtherActivity if required.
