### ISSUE TITLE
Extra optional parameter for Dismount 

### ISSUE THREAD

**Issue by hendersonhc** [AMSP-04/NETN-ETR#64]
Add an optional  dismount location (WorldLocationStruct). The attached entity is dismount at the given position.
First the attached entity dismount at the same location as the entity to which it is attached and then moves to the location given in this parameter.

**Comment by lofstrandbjorn** [comment]
This could also be accomplished with a Dismout followed by a MoveToLocation task. A MoveToLocation task on a mounted entity

**Comment by lofstrandbjorn** [comment]
Consider name change. **Attach/Detach.**
Do dismount (detach) implicitly if Move task is accepted.
Change mount/dismount to attach/detach everywhere.

**Comment by lofstrandbjorn** [comment]
Updated.
