### ISSUE TITLE
Extra parameter MoveToLocation

### ISSUE THREAD

**Issue by hendersonhc** [AMSP-04/NETN-ETR#65]
It should also be possible to define the optional path with a list of objects (uuid) instead of a list of locations or by an uuid of a path object.

In that case is is possible that the movement passes special waypoints or engineer bridges by using the location on which this objects are defined.
So an extra optional parameters pathByObjects of type ArrayOfUuid is needed

**Comment by lofstrandbjorn** [comment]
This issue has already been discussed, and the conclusion was to limit the options on how to express locations (not only waypoints in the MoveToLocation task but on other tasks as well). The location of an object can be copied and put explicitly into the Move Task.

**Comment by lofstrandbjorn** [comment]
Investigate adding info on segments in a path e.g. bridge, road etc. + additional info on max weight, width etc.

**Comment by lofstrandbjorn** [comment]
MoveByRoute task is updated to accommodate for more information on each segment.

**Comment by lofstrandbjorn** [comment]
Updated the Waypoint datatype to include SegmentMaxWidth in meters.
