### ISSUE TITLE
Extra parameter MoveToLocattion (2)

### ISSUE THREAD

**Issue by hendersonhc** [AMSP-04/NETN-ETR#66]
When an aggregate (in aggregate level mode) moves through the terrain it occupies a certain area and the area can be to large to pass narrow passages between forest/buildings.
In real situations the aggregate can temporary change from a deployed formation to a column formation, then pass to narrow lane between the forest/buildings and when passed goes back to deployed formation again. An other option is not to go through the narrow lane and find another route around the forest/buildings.
To tell the simulation this behaviour an extra optional boolean parameter useColumnWdth is needed to tell the aggregate (when set to true) that passing through narrow lanes is allowed.

**Comment by lofstrandbjorn** [comment]
Let's discuss on telecon.

**Comment by lofstrandbjorn** [comment]
Add to semantics a description of how this applies to aggregate entities simulated on an "aggregate level".

**Comment by lofstrandbjorn** [comment]
Solved by using MoveByRoute and the added SegmentMaxWidth data for each waypoint.
